### ISSUE TITLE
Warning: AnimatorParameter and UnityMember override Object.Equals(object) but does not override Object.GetHashCode()

### ISSUE THREAD

**Issue by hsandt** [lazlo-bonin/ludiq-reflection#1]
The usual warning when overriding Equals but not GetHashCode, as we should ensure that objects that are considered equal have the same hash code, in case they are used in HashSet, Dictionary, etc.

> Assets/Plugins/Ludiq/Reflection/Reflection/AnimatorParameter.cs(7,15): warning CS0659: `Ludiq.Reflection.AnimatorParameter' overrides Object.Equals(object) but does not override Object.GetHashCode()

> Assets/Plugins/Ludiq/Reflection/Reflection/UnityMember.cs(13,15): warning CS0659: `Ludiq.Reflection.UnityMember' overrides Object.Equals(object) but does not override Object.GetHashCode()

**Comment by lazlo-bonin** [comment]
Unfortunately, I'm no longer maintaining this repository. I'm working on a much more robust Unity reflection library which has fixed this issue already, but I have no time frame for its release.

**Comment by hsandt** [comment]
OK, so for the time coming I'll implement a simple hash code to suppress the warning. Good luck for the new framework!
