### ISSUE TITLE
Setting a UnityMember field changes the next one instead

### ISSUE THREAD

**Issue by hsandt** [lazlo-bonin/ludiq-reflection#2]
When multiple UnityMember fields are editable in the Inspector, setting the member on one field changes the member on the next one instead (if there is any).

On the screenshots you can see me edit the 1st field member, but the 2nd one gets modified instead. Since the game object on the 2nd field is not the same, the method will be invalid when called runtime.

![bug ludiq reflection unitymemberdrawer setting field changes next one - 1](https://cloud.githubusercontent.com/assets/1067772/25502689/f6a90f7c-2b97-11e7-8f95-545c885723b0.png)

![bug ludiq reflection unitymemberdrawer setting field changes next one - 2](https://cloud.githubusercontent.com/assets/1067772/25503184/ad085f1a-2b99-11e7-81b2-5bdbef5c25e9.png)

![bug ludiq reflection unitymemberdrawer setting field changes next one - 3](https://cloud.githubusercontent.com/assets/1067772/25502688/f6a8cb98-2b97-11e7-81c4-1b06ed557d51.png)

The bug occurs even when there is another type of field between the UnityMembers.

I had a quick look at UnityMemberDrawer but I can't find anything suspicious. I thought some static variable or something was used and leaked from a drawer to the other, but no. `nameProperty `seems in order.

For now, I go into Debug mode in the Inspector and set the component name and member name manually.

Note: the bug was not here in the previous version, where I saw using UnityMethod instead of UnityMember.

**Comment by lazlo-bonin** [comment]
This issue is caused by faulty immediate mode GUI handling in DropdownGUI from Ludiq.Controls:

https://github.com/lazlo-bonin/ludiq-controls/blob/master/Controls/Editor/DropdownGUI.cs

Unfortunately, I'm no longer maintaining either repositories. I'm working on a much more robust Unity reflection library which will replace them both, but I have no time frame for its release.
